In [2]:
import numpy as np
print(np.__version__)

2.4.6


In [3]:
arr = np.array([1, 2, 3, 5])
print(arr)
print(type(arr))

[1 2 3 5]
<class 'numpy.ndarray'>


# 0D Array

In [4]:
arr = np.array(22)
print("Array:")
print(arr)
print(f"{arr.ndim} dimension array")

Array:
22
0 dimension array


# 1D Array

In [5]:
arr = np.array([1, 2, 3])
print("Array:")
print(arr, "\n")
print(f"{arr.ndim} dimension array")

Array:
[1 2 3] 

1 dimension array


# 2D Array

In [6]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
print("Array:")
print(arr, "\n")
print(f'''{arr.ndim} dimension array''')

Array:
[[1 2 3]
 [1 2 3]] 

2 dimension array


# 3D Array

In [7]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print("Array:")
print(arr, "\n")
print(f'''{arr.ndim} dimension array''')

Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 

3 dimension array


In [8]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


# Accessing values by indes - 1D, 2D, 3D, MD

In [17]:
arr1 = np.array([1, 2, 3, 5])
print(arr1[0])
print(arr[2])

1
3.0


In [ ]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
print(arr[0, 1])
print(arr[1, 2])

2
3


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arr[0, 2, 1])
print(arr.ndim)

8
3


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]], 
                [[2, 22, 12], [66, 90, 88]], 
                [[2, 22, 12], [66, 343, 88]]])

print(arr[3, 1, 1])

print(arr[-1,1,-2])

343
343


# Slicing 

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[2:-1])
print(arr[4:])
print(arr[::-1])
print(arr[1:5:2])
print(arr[::2])
print(arr1[0:2, 2])

[3 4 5 6]
[5 6 7]
[7 6 5 4 3 2 1]
[2 4]
[1 3 5 7]
[3 8]


# Datatypes 
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int64
<U6


In [16]:
# Creating array with diff. data type

arr = np.array([1,2,3,4,5], dtype="f")
arr1 = np.array([1, 2, 3, 4], dtype='S')

print(arr, arr.dtype)
print(arr1, arr1.dtype)

[1. 2. 3. 4. 5.] float32
[b'1' b'2' b'3' b'4'] |S1


In [18]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')
print(newarr)

[1 2 3]
